from enum import Enum, unique


@unique
class Classifier(Enum):
    ADA_BOOST_CLASSIFIER = 1
    BERNOULLI_NB = 2
    COMPLEMENT_NB = 3
    DECISION_TREE_CLASSIFIER = 4
    K_NEIGHBORS_CLASSIFIER = 5
    LINEAR_SVC = 6
    LOGISTIC_REGRESSION = 7
    MULTINOMIAL_NB = 8
    NEAREST_CENTROID = 9
    PASSIVE_AGGRESSIVE_CLASSIFIER = 10
    PERCEPTRON = 11
    RANDOM_FOREST_CLASSIFIER = 12
    RIDGE_CLASSIFIER = 13
    SGD_CLASSIFIER = 14
