from enum import Enum, unique


@unique
class Classifier(Enum):
    ADA_BOOST_CLASSIFIER = 1
    BERNOULLI_NB = 2
    DECISION_TREE_CLASSIFIER = 3
    K_NEIGHBORS_CLASSIFIER = 4
    LINEAR_SVC = 5
    LOGISTIC_REGRESSION = 6
    MULTINOMIAL_NB = 7
    NEAREST_CENTROID = 8
    PASSIVE_AGGRESSIVE_CLASSIFIER = 9
    PERCEPTRON = 10
    RANDOM_FOREST_CLASSIFIER = 11
    RIDGE_CLASSIFIER = 12
    SGD_CLASSIFIER = 13
